# http://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html
sudo: false

language: scala

jdk: oraclejdk8

scala:
  - 2.11.8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
  - sbt coveralls

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete